return function()
    leds=require 'leds'
    leds:init(60, 8)
    buf = ws2812.newBuffer(leds.total, 3)
    color = string.char(0, 0, 0)
    buf:fill(color:byte(1,3))
    leds:write(buf)    
    next_color = string.char(42,42,42)
    dofile("mqconsole.lc")()
    leds:write(string.rep(color,leds.total))
    nt.mqtt:subscribe('actuators/led',0, function(msg)
        local iter = string.gmatch(msg, '%d+')
        local r, g, b = tonumber(iter()),tonumber(iter()),tonumber(iter())
        print('!!',r, g, b)
        print(node.heap())
        next_color = string.char(g, r, b)
    end)
end
